### ISSUE TITLE
FG Account Business - Image Pairing- 'Burrito'- Not identical images please resolve 

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#100]
I am not a robot- The image shown to verify was different than the orginal. However, I selected two similar items and it accpeted the verfication. This step wihtout the exact matching image is confusing. /Users/elizabethblackmore/Desktop/Screen shot 2015-05-13 at 1.21.42 PM.png

**Comment by viplavfauzdar** [comment]
That recaptcha is all google. I don't have any control over it.
