### ISSUE TITLE
FG Account ACC Sign-Up 'Code' with 'Captacha'

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#109]
![screen shot 2015-05-13 at 5 14 31 pm](https://cloud.githubusercontent.com/assets/10566236/7621560/befbd298-f995-11e4-98d2-6fb1b50df1c4.png)

Why is it necessary to have both security measures in place to determine whether whoever is a robot or not? Why have more barriers than necessary? Does it have to do with them being an investor, if so copying code is suffice to show not robot but human

**Comment by viplavfauzdar** [comment]
Read up on DOS - denial of service. I can write a small program that can take any website down if it wasn't for this extra precaution and I am not even a hacker.
