### ISSUE TITLE
FG Account NON-ACC Sign-Up 'Nothing Verified Me' Meaning I could be a Robot

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#110]
![screen shot 2015-05-13 at 5 46 37 pm](https://cloud.githubusercontent.com/assets/10566236/7621817/d45353a8-f997-11e4-82cf-d2497151c026.png)

**Comment by viplavfauzdar** [comment]
Nope. By now google knows you are not a bot thats why it didn't ask. They use some complex algorithm to figure out who and when to prompt.
