### ISSUE TITLE
FG Account NON-PROFIT contact- Generates Generic Response  

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#129]
![screen shot 2015-05-14 at 1 34 38 pm](https://cloud.githubusercontent.com/assets/10566236/7637685/c5a16812-fa3d-11e4-8ad0-641cf3942501.png)
![screen shot 2015-05-14 at 1 34 52 pm](https://cloud.githubusercontent.com/assets/10566236/7637686/c6b489dc-fa3d-11e4-8a34-bffc68678420.png)
The personalization Tool is not effective

**Comment by viplavfauzdar** [comment]
working on the email templates for different types of emails.
