### ISSUE TITLE
FG Account Sign-Up 'Contact' (FOR ALL 4- Business, Investor (Acc or non-Acc) Non-profit) Steps after should remove typing

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#130]
![screen shot 2015-05-14 at 1 36 20 pm](https://cloud.githubusercontent.com/assets/10566236/7637749/22106800-fa3e-11e4-9364-f9f0f8ed50ca.png)
![screen shot 2015-05-14 at 1 36 43 pm](https://cloud.githubusercontent.com/assets/10566236/7637752/232d6a08-fa3e-11e4-9742-83ed19a8ae8a.png)

As seen the typing disappeared ONLY after I opened a new page "FAQ" (ISSUE- why not automatically remove when I was noticed it confirmed and received an email for all 4 accounts whether business, investor (acc or non-acc) or non-profit).

**Comment by viplavfauzdar** [comment]
non-issue
