### ISSUE TITLE
FG Account 'Non-profit' P-info-  'Elizabeth' 

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#131]
![screen shot 2015-05-14 at 3 31 18 pm](https://cloud.githubusercontent.com/assets/10566236/7639991/33d5aec8-fa4e-11e4-8703-8e0db225f743.png)
![screen shot 2015-05-14 at 3 32 44 pm](https://cloud.githubusercontent.com/assets/10566236/7639992/34c7a764-fa4e-11e4-802a-c461500c9047.png)

**Comment by viplavfauzdar** [comment]
space??
