### ISSUE TITLE
FG Account 'Non-profit' P-info- 'Elizabeth' - 'City Error' - NOTHING FURTHER 

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#133]
![screen shot 2015-05-14 at 3 36 53 pm](https://cloud.githubusercontent.com/assets/10566236/7640126/5258d1f8-fa4f-11e4-93ea-65e86cbf38fd.png)
![screen shot 2015-05-14 at 3 38 01 pm](https://cloud.githubusercontent.com/assets/10566236/7640129/546c012c-fa4f-11e4-801b-47ff1d8aa21d.png)
![screen shot 2015-05-14 at 3 40 02 pm](https://cloud.githubusercontent.com/assets/10566236/7640130/55aedfa0-fa4f-11e4-8629-8ff65fd0abc5.png)
![screen shot 2015-05-14 at 3 40 08 pm](https://cloud.githubusercontent.com/assets/10566236/7640132/56545188-fa4f-11e4-9e91-02ee52ecbdb8.png)

So even though Elizabeth is Letters from previous error, I changed to EH to proceed through the steps, however, somebody else will not. Then the City Error stopped the process of anything further from , to legal documents to bank accounts.

**Comment by viplavfauzdar** [comment]
Fixed.
