### ISSUE TITLE
FG Account 'Acc-Investor' P-info- 'Elizabeth' (location information) section

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#135]
![screen shot 2015-05-14 at 3 56 03 pm](https://cloud.githubusercontent.com/assets/10566236/7640486/80c3643e-fa51-11e4-8ad5-8e8ee184adca.png)

City Error
![screen shot 2015-05-14 at 3 56 21 pm](https://cloud.githubusercontent.com/assets/10566236/7640487/81ca3bf0-fa51-11e4-9f1b-6ac0d6900a14.png)

City Error 

Essentially if I wanted to continue changing until it satisfied the system knowing we need to test would not make a lot of sense, because the end-user will not continue to enter invalid city that they don;t live in to get to next steps. So I keep changing the user info to get to location info, however, how do we not know these errors exist cause they seem really really simple

**Comment by viplavfauzdar** [comment]
Same thing. You are adding a space at the end. why?
