### ISSUE TITLE
FG Account 'NON-Acc-Investor' P-info- 'Elizabeth'

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#136]
Same Errors as with the non-profit and Acc investor Fillout 
![screen shot 2015-05-14 at 4 04 22 pm](https://cloud.githubusercontent.com/assets/10566236/7640672/a5ce4fcc-fa52-11e4-8fa2-ea2b4b52688e.png)

**Comment by viplavfauzdar** [comment]
Same thing. You are adding a space at the end. why?
