### ISSUE TITLE
  Edit New issue FG Account 'Business' P-info- 'Elizabeth'

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#137]
![screen shot 2015-05-14 at 4 04 22 pm](https://cloud.githubusercontent.com/assets/10566236/7640710/f0c14e62-fa52-11e4-8c41-764aa35c12de.png)

Same Errors as with the Non-profit, Investor (Acc. or Non-Acc), also happening in the Fillout

**Comment by viplavfauzdar** [comment]
There is a space at the end that's why. This is a low priority. I'll come to it later.
