### ISSUE TITLE
Change Wording and date

### ISSUE THREAD

**Issue by choncholg** [viplavfauzdar/tommy#155]
copywrite 2015

Thank you for signing up! We welcome you to Finance Georgia. You are now an important member of the Georgia investment community. 

![screen shot 2015-05-31 at 11 12 45 pm](https://cloud.githubusercontent.com/assets/10608456/7905681/9429f60e-07ea-11e5-93e2-30675f2e9873.png)

**Comment by viplavfauzdar** [comment]
done. changed copy right everywhere
