### ISSUE TITLE
Address capitalized

### ISSUE THREAD

**Issue by choncholg** [viplavfauzdar/tommy#158]
For some reason, the address is entered capitalized correctly in the profile page, but is lowercased on the listing.

![screen shot 2015-06-01 at 11 54 56 am](https://cloud.githubusercontent.com/assets/10608456/7917000/35ee7de2-0855-11e5-87a7-5205aa76e144.png)
![screen shot 2015-06-01 at 11 55 09 am](https://cloud.githubusercontent.com/assets/10608456/7916999/35ecfb5c-0855-11e5-8314-de1faa9e8744.png)

**Comment by viplavfauzdar** [comment]
done in portfolio by adding text-transform
