### ISSUE TITLE
Fix website fill in for accredited investor

### ISSUE THREAD

**Issue by choncholg** [viplavfauzdar/tommy#172]
Someone should be able to put "www.chonchol.com" or "chonchol.com". They should not have to enter "http://www.chonchol.com"

![screen shot 2015-06-03 at 12 35 30 am](https://cloud.githubusercontent.com/assets/10608456/7952767/2602c99e-0989-11e5-9791-28a8b3cddc8c.png)
![screen shot 2015-06-03 at 12 35 50 am](https://cloud.githubusercontent.com/assets/10608456/7952769/2623043e-0989-11e5-80f0-bebb1aadede9.png)
![screen shot 2015-06-03 at 12 36 08 am](https://cloud.githubusercontent.com/assets/10608456/7952768/2620dd3a-0989-11e5-96e1-b33fc6d2e5dc.png)

**Comment by viplavfauzdar** [comment]
That's a javascript validation library I am using. I'll change this later.
