### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by choncholg** [viplavfauzdar/tommy#173]
"Thank You for signing up for Finance Georgia. Now, click HERE to complete your profile. You are just one step away from being able to invest through our platform.

Before you can make your first investment, you must complete the user profile and e-sign the legal agreements listed in that section. We look forward to having you as an investor.

![screen shot 2015-06-03 at 12 34 01 am](https://cloud.githubusercontent.com/assets/10608456/7952790/56a2213a-0989-11e5-9fb7-924a25a285d1.png)

**Comment by viplavfauzdar** [comment]
done
