### ISSUE TITLE
WEB FORWARDING is a NO GO

### ISSUE THREAD

**Issue by viplavfauzdar** [viplavfauzdar/tommy#174]
Causing JS errors in console - uncaught ReferenceError: usrObj is not defined.
Also issue with responsive because of frames.

**Comment by viplavfauzdar** [comment]
Nah - seem to be getting the 1st error in QA too. Why?
Also 2nd is not urgent 'cause we don't have SSL cert yet. However with FG right now we don't have SSL working (or at least I can't tell)

**Comment by dhatami** [comment]
Why don't we have a cert? It seems pretty fundamental no?

**Comment by viplavfauzdar** [comment]
don't worry about it. We don't need it with web forwarding. This is notes for myself cause I tend to forget.

**Comment by viplavfauzdar** [comment]
Redhat service is SSL. With web forwarding we don't see that message in the browser because the browser thinks the SSL is for FG and not Redhat.
