### ISSUE TITLE
Design Aesthetic and Language 

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#21]
About Page- (also links on at the bottom of each individual page too- 'Learn More") thereby its important. 
1. Replace Images (replace with anything, even another skyline of Atlanta)! 
2. The Language 'Hot' Georgia Companies is unequivocally unprofessional. 
   LinkedIn Description is more reflective
   -LinkedIn- 
   Finance Georgia is a pioneer of economic freedom for Georgia's entrepreneurs and investors. The usage of equity crowd funding connects investors and communities in a mutually beneficial way. Economic development is achieved through meeting the capital needs of Georgia's companies and investors returns are maximized by utilizing the invest Georgia exemptions, the significant Angel tax credits and an extensive due diligence process.

**Comment by viplavfauzdar** [comment]
All the design/content/language needs a review. This is an action item for the team and we need to get together on it once all functional testing is done.
