### ISSUE TITLE
Design Aesthetic and Language - Slogans

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#22]
E-Trade

I have never used E-trade in my life, and do not know how it correlates to FG other than removes the need of a broker through the change of legistative laws. Through the perspective lens of the end-user, utilizing our site without financial repertoire- the E-trade slogan is meaningless. Furthermore, are we a site that promotes E-Trade, is E-Trade a sponsor... People could perhaps consider that?  Also, as 'off' as this sounds, some people in the more established financial community and sophisticated millennials don't even know what Kickstarter is. Sometimes I try to explain FG with an introduction baseline of "like a Kickstarter with Equity' 

Two slogans that we need to alter is:
'E-trade'
'Why invest on Wall Street, when you can invest in Peachtree Street?'- Love the locality of this but can be enhanced. 'Georgia Companies meet Georgia Investors"

**Comment by viplavfauzdar** [comment]
All the design/content/language needs a review. This is an action item for the team and we need to get together on it once all functional testing is done.
