### ISSUE TITLE
Business- Sign-Up (Verify reCAPTCHA)

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#23]
1. The process worked (completed with checks) until the end of 'Sign-Up" it circled but didn't proceed to next screen without confirming the reCAPTCHA. 
2. The top upper right corner from screen says "Please Verify reCAPTCHA' 
   /Users/elizabethblackmore/Desktop/Screen shot 2015-01-16 at 6.59.43 PM.png
   /Users/elizabethblackmore/Desktop/Screen shot 2015-01-16 at 6.59.50 PM.png

**Comment by viplavfauzdar** [comment]
That isexpected functionality. The captcha thing is to make sure the users are real people and not computer programs.
