### ISSUE TITLE
Mobile View- 'Drop Down Menu" Top Right from Screen  

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#25]
For whatever reason the mobile device does not provide options in terms of individual pages from the drop-down menu located within the three-dash screen 
/Users/elizabethblackmore/Desktop/Screen shot 2015-01-16 at 7.16.39 PM.png

**Comment by viplavfauzdar** [comment]
Don't test on mobile just yet. I have to come back to it and see why the responsive behavior is broken!
