### ISSUE TITLE
Business Sign-Up 

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#26]
Intially when browsing the site, the top bar Options of Home -to Sign-Out changed even though the Sign-Up didn;t work. 
 /Users/elizabethblackmore/Desktop/Screen shot 2015-01-16 at 7.18.00 PM.png

So first time on the site, 
I thought I saw a 'Sign-up" option next to the 'Sign-out" option. in the top bar?!
So I go to utilize the "business Sign-Up' option - at the reCAPTCHA stage it stops preocess (noted earlier 23) and then the top menu bar went from 'Sign-Up" to 'Account"?!

 Even thought the account didn't process properly. Somehow it seems as though it even if I refresh the browser, restart chrome, whatever, the account option is there even though I have not been notified via email at Revision3777@gmail.com of an account creation form FG Business

**Comment by viplavfauzdar** [comment]
fixed
