### ISSUE TITLE
Investor - Accredited Sign-up

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#27]
Process works (accompanied by checks), then finalize the Sign-Up image appears top right from screen- says 'Object, Object" 

/Users/elizabethblackmore/Desktop/Screen shot 2015-01-16 at 7.29.07 PM.png/Users/elizabethblackmore/Desktop/Screen shot 2015-01-16 at 7.29.15 PM.png

**Comment by viplavfauzdar** [comment]
fixed
