### ISSUE TITLE
Investor- Un-Accredited Sign-Up

### ISSUE THREAD

**Issue by eblackmore** [viplavfauzdar/tommy#29]
Process is accompanied by checks, then to order to proceed with the sign-up again, the reCAPTCHA image appears top right from screen /Users/elizabethblackmore/Desktop/Screen shot 2015-01-16 at 7.41.11 PM.png/Users/elizabethblackmore/Desktop/Screen shot 2015-01-16 at 7.41.18 PM.png

Also, I have yet to recieve any emails from FG notifying me of any account set-up

**Comment by viplavfauzdar** [comment]
fixed
