### ISSUE TITLE
Portfolio Business pictures

### ISSUE THREAD

**Issue by choncholg** [viplavfauzdar/tommy#32]
I want to make sure that the correct pictures are showing up for the correct companies. For example, when I click to view details on Initech, I see a picture of Pepsi. I know that these might just be placeholders, but I want to make sure that the pepsi picture is not being pulled form the wrong place. I.e. that teh Pepsi picture has been reigstered as a picture for Initech.

**Comment by viplavfauzdar** [comment]
was an issue with the uploader servlet fixed now.
