### ISSUE TITLE
"Signup" buttons at the bottom of the home page

### ISSUE THREAD

**Issue by choncholg** [viplavfauzdar/tommy#35]
1- if you are logged in as a user already, they shouldnt appear. Not sure how hard that is to fix, but it is a nice to have- not a must have
2- Just have a "signup as an investor or business", because it still makes the user choose "business" or "investor"... If they miss that button, they might sign up as the wrong thing..

2 should be discussed... because it might be trivial.

**Comment by choncholg** [comment]
ALso- it still says "Ready to Sign Up for Finance Georgia?" at the bottom, if you are logged in, and if you are looking at the portfolio companies.

**Comment by viplavfauzdar** [comment]
fixed
