### ISSUE TITLE
Main Images (Aesthetic)

### ISSUE THREAD

**Issue by dhatami** [viplavfauzdar/tommy#5]
Would like to add an image that is non Atlanta. 
Examples:
http://fitsnews.com/wp-content/uploads/2011/11/nikki-haley-dhec-savannah-port.jpg
http://www.porttechnology.org/images/sized/images/uploads/news/sunset_savannah_port1-600x0.jpg
http://www.bryanstovall.com/stovall/sites/default/files/imagecache/lightbig/City-Hall-with-Bridge.png

**Comment by viplavfauzdar** [comment]
You need to provide me the specific pictures and make sure they are high-res.
