### ISSUE TITLE
Sign Up: Can't go back to prior fields

### ISSUE THREAD

**Issue by dhatami** [viplavfauzdar/tommy#53]
I understand why you can't proceed before fields are OK, however you don't have the ability to go back either.  In this case I mistyped an initial password, cant see what it was and have no way of correcting it (and can't continue since I dont know what it is to match)

**Comment by dhatami** [comment]
![screenshot 2015-03-13 at 11 25 40 pm](https://cloud.githubusercontent.com/assets/10552509/6650118/8915e46c-c9d8-11e4-8bbf-94120e602e59.png)

**Comment by viplavfauzdar** [comment]
Not sure I want to change this. You can simply refresh the page and fill the form out again. If I change it then it breaks this functionality in a number of other places.

**Comment by viplavfauzdar** [comment]
disabled force focus for now.
