### ISSUE TITLE
Sign Up: Recaptcha 

### ISSUE THREAD

**Issue by dhatami** [viplavfauzdar/tommy#55]
Keeps asking me to verify or shows error, no option to enter. 
![screenshot 2015-03-13 at 11 32 24 pm](https://cloud.githubusercontent.com/assets/10552509/6650131/439efee0-c9d9-11e4-9427-8369ecd6e89b.png)

**Comment by viplavfauzdar** [comment]
not an issue. dupe emails not allowed
