### ISSUE TITLE
Sign up as: Defaults to Business

### ISSUE THREAD

**Issue by dhatami** [viplavfauzdar/tommy#57]
Even when clicking sign-up as an investor, sign up page "registration type" still defaults to "business"
![screenshot 2015-03-13 at 11 36 29 pm](https://cloud.githubusercontent.com/assets/10552509/6650159/f36d8e0e-c9d9-11e4-9633-dd5bcf4d0507.png)

**Comment by viplavfauzdar** [comment]
fixed. added hash to links register.html#investor and jq in register,html
