### ISSUE TITLE
Password retrieval/reset process is awkward 

### ISSUE THREAD

**Issue by dhatami** [viplavfauzdar/tommy#70]
I understand the need for security but the process isn't user friendly.
1) First made to put in email (ok)
2) Then made to click link (ok)
3) Then it sends a temp (ok, but way too long. Example: 7prf22oik5g7fo46unm510kgi , how will someone type this in if they don't know how to copy and paste?)
4) The page sent to has no navigation and requires another reload etc. (see attached)
![screenshot 2015-03-25 at 12 18 43 pm](https://cloud.githubusercontent.com/assets/10552509/6829317/1f8fad74-d2e9-11e4-9f08-389b382f4eb6.png)

**Comment by viplavfauzdar** [comment]
fixed. reduced the generated password lengh. changed the page above to below.

![image](https://cloud.githubusercontent.com/assets/4999809/6833163/6886bb72-d301-11e4-9df0-db0afe985599.png)
