### ISSUE TITLE
My Account: Invests Issue 

### ISSUE THREAD

**Issue by dhatami** [viplavfauzdar/tommy#73]
Error when trying to look at investments (see enclosed)
![screenshot 2015-03-25 at 6 39 10 pm](https://cloud.githubusercontent.com/assets/10552509/6837039/6022f9d8-d31e-11e4-9f4c-1e9701f55fa8.png)

**Comment by viplavfauzdar** [comment]
My bad. Forgot to add the new field in the QA database.

**Comment by viplavfauzdar** [comment]
added the field.
