### ISSUE TITLE
Address: Forced to fill in Website and Social Links

### ISSUE THREAD

**Issue by dhatami** [viplavfauzdar/tommy#82]
Won't save otherwise Don't make those mandatory fields.
![screenshot 2015-04-08 at 12 09 58 pm](https://cloud.githubusercontent.com/assets/10552509/7049532/540afbee-dde8-11e4-8398-7b5a5f81d15f.png)

**Comment by viplavfauzdar** [comment]
took it out already. will be pushed with the next build.
