### ISSUE TITLE
Bank Account: Error when saving

### ISSUE THREAD

**Issue by dhatami** [viplavfauzdar/tommy#84]
Error occurs when saving info
![screenshot 2015-04-08 at 12 13 20 pm](https://cloud.githubusercontent.com/assets/10552509/7049598/b619ee30-dde8-11e4-8d35-ca1f3ef65e19.png)

**Comment by viplavfauzdar** [comment]
It is because you didn't fill out the user/location info aka name and address. I'll add some error checking for it.

The other thing is that in the dev balanced account the ACH verification amounts are 1 & 1 each

**Comment by viplavfauzdar** [comment]
added js validation for usr check before bus tab click
