### ISSUE TITLE
Didn't ask for CAPTCHA

### ISSUE THREAD

**Issue by dhatami** [viplavfauzdar/tommy#9]
![image](https://cloud.githubusercontent.com/assets/10552509/5766234/d377819c-9ccd-11e4-8a7b-2057f96803c3.png)
Doesn't ask for CAPTCHA upon initial sign up, only does so after edit etc.

**Comment by viplavfauzdar** [comment]
Google uses some intelligent logic and doesn't offer the image everytime.
