### ISSUE TITLE
fgDialogBS - messing up font (look at change pass or pass reset dialog)

### ISSUE THREAD

**Issue by viplavfauzdar** [viplavfauzdar/tommy#93]
![image](https://cloud.githubusercontent.com/assets/4999809/7403301/56ba6ab2-eea2-11e4-897d-6b668ca18d0d.png)

**Comment by viplavfauzdar** [comment]
This one is fine. Even h4 messes up above. had to use h3.

![image](https://cloud.githubusercontent.com/assets/4999809/7403317/783cda30-eea2-11e4-87c9-ac764703cc06.png)

**Comment by viplavfauzdar** [comment]
The above issue happens even is I can fgModal directly. The change pass above is fine cause I am using a URL instead

The issue may have something to do with the order of js libs esp functions.js

**Comment by dhatami** [comment]
Give me the best login and url for demo plz

**Comment by viplavfauzdar** [comment]
doesnt happen in QA. only in DEV. weird
